version: '3.8'
services:
    db:
        image: mysql
        environment:
            MYSQL_DATABASE: shorten-link
            MYSQL_ROOT_PASSWORD: xkA1siXB
        ports: 
            - 3306:3306
    backend:
        build:
            context: ../shortenLinkServer
            dockerfile: Dockerfile
        image: shorten-link-production-backend
        restart: unless-stopped
        environment: 
            - PORT=3001
            - DB_USERNAME=root
            - DB_PASSWORD=xkA1siXB
            - DB_NAME=shorten-link
            - DB_HOST=db
            - DB_DIALECT=mysql
            - NODE_ENV=production
            - JWT_SECRET=xkA1siXB+m2m+/kaK2MATA   
            - JWT_EXPIRES_IN=720h
            - REACT_URL=http://backend-env.eba-nq3xkju3.us-east-1.elasticbeanstalk.com/        
            - BACK_END_URL=http://backend-env.eba-nq3xkju3.us-east-1.elasticbeanstalk.com/api/
            - GOOGLE_CLIENT_ID=805934574997-bd9v031en51211shhuulidl3v0ejf6r2.apps.googleusercontent.com
            - GOOGLE_CLIENT_SECRET=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
        depends_on:
            - db
        ports: 
            - 3001:3001
        expose:
            - 3001
    nginx:
        image: nginx:1.23.3
        ports:
            - 3000:3000
        volumes:
            - ../shortenLinkClient/build/:/usr/share/nginx/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - backend