version: '2'
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 123456
            MYSQL_DATABASE: shorten_link
    Mongo:
        image: mongo
        ports:
            - "27017:27017"
    backend:
        build:
            context: ../shortenLinkServer
            dockerfile: Dockerfile
        restart: unless-stopped
        environment: 
            - DB_HOST=host.docker.internal
        # ports:
        #     - 8080:8080
        expose:
            - 8080
    nginx:
        image: nginx:1.23.3
        ports:
            - 80:80
        volumes:
            - ../shortenLinkClient/build/:/usr/share/nginx/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
