version: '3.8'
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: 1
            POSTGRES_USER: postgres
            POSTGRES_DB: shorten_link
    mongo:
        image: mongo
    redis:
        image: redis
    backend:
        build:
            context: ../shortenLinkServer
            dockerfile: Dockerfile
        image: shorten-link-production-backend
        restart: unless-stopped
        environment: 
            - PORT=8080
            - DB_USERNAME=postgres
            - DB_PASSWORD=1
            - DB_NAME=shorten_link
            - DB_HOST=db
            - DB_DIALECT=postgres
            - NODE_ENV=production
            - MONGODB_URL=mongodb://mongo/shorten_link
            - REDIS_URL=redis://redis
            - JWT_SECRET=xkA1siXB+m2m+/kaK2MATA   
            - JWT_EXPIRES_IN=720h
            - REACT_URL=http://54.169.52.161/        
            - BACK_END_URL=http://54.169.52.161/api/  
            - GOOGLE_CLIENT_ID=805934574997-bd9v031en51211shhuulidl3v0ejf6r2.apps.googleusercontent.com
            - GOOGLE_CLIENT_SECRET=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
        depends_on:
            - db
            - redis
            - mongo
        expose:
            - 8080
    redirector:
        build:
            context: ../shortenLinkRedirector
            dockerfile: Dockerfile
        image: shorten-link-production-redirector
        restart: unless-stopped
        environment: 
            - PORT=8081
            - STORE_SERVICE_URL=http://backend:8080/ 
            - STORE_SERVICE_VISIT=http://backend:8080/link/visit/
            - MONGODB_URL=mongodb://mongo/shorten_link
            - REDIS_URL=redis://redis
        ports:
            - 8081:8081
        depends_on:
            - db
            - redis
            - mongo
    nginx:
        image: nginx:1.23.3
        ports:
            - 80:80
        volumes:
            - ../shortenLinkClient/build/:/usr/share/nginx/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - backend